services:
    ms-ad-api:
        build:
            context: ./.docker/php/runtime/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP-1000}'
        container_name: ms-ad-api
        image: laravel-php8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8001:80'
        env_file:
            - ./.env
            - ./ms-ad-api/.env
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './ms-ad-api:/var/www/html'
        networks:
            - ms-communication-and-search
        depends_on:
            - mysql
            - rabbitmq
            # - redis
    ms-consumer-api:
        build:
            context: ./.docker/php/runtime/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP-1000}'
        container_name: ms-consumer-api
        image: laravel-php8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8002}:80'
        env_file:
            - ./.env
            - ./ms-consumer-api/.env
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DB_HOST: '${MYSQL_DB_HOST}'
            DB_PORT: '${MYSQL_DB_PORT}'
            DB_USERNAME: '${MYSQL_DB_USERNAME}'
            DB_PASSWORD: '${MYSQL_DB_PASSWORD}'
        volumes:
            - './ms-consumer-api:/var/www/html'
        networks:
            - ms-communication-and-search
        depends_on:
            - mysql
            - rabbitmq
            # - redis
    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        ports:
            - '${MYSQL_DB_FORWARD_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_USER: '${MYSQL_DB_USERNAME}'
            MYSQL_PASSWORD: '${MYSQL_DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'ms-communication-and-search-mysql:/var/lib/mysql'
            - './.docker/mysql/create-databases.sh:/docker-entrypoint-initdb.d/10-create-databases.sh'
        networks:
            - ms-communication-and-search
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        hostname: "rabbit"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            NAME: "rabbitmq"
            # USER: "guest"
            # PASS: "guest"
        volumes:
            - ./.docker/rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
        networks:
            - ms-communication-and-search
    # redis:
    #     image: 'redis:alpine'
    #     ports:
    #         - '${FORWARD_REDIS_PORT:-6379}:6379'
    #     volumes:
    #         - 'sail-redis:/data'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - redis-cli
    #             - ping
    #         retries: 3
    #         timeout: 5s
networks:
    ms-communication-and-search:
        driver: bridge
volumes:
    ms-communication-and-search-mysql:
        driver: local
