services:
    ms-ad-api:
        extends:
            file: ./ms-ad-api/docker-compose.yml
            service: ms-ad-api
        env_file:
            - ./ms-ad-api/.env
        volumes:
            - './ms-ad-api:/var/www/html'
        networks:
            - database
            - rabbitmq
        depends_on:
            - mysql
            - rabbitmq
    ms-consumer-api:
        extends:
            file: ./ms-consumer-api/docker-compose.yml
            service: ms-consumer-api
        env_file:
            - ./ms-consumer-api/.env
        volumes:
            - './ms-consumer-api:/var/www/html'
        networks:
            - database
            - rabbitmq
            - elasticsearch
        depends_on:
            - mysql
            - rabbitmq
            - elasticsearch
    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        ports:
            - '${MYSQL_DB_FORWARD_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_USER: '${MYSQL_DB_USERNAME:-username}'
            MYSQL_PASSWORD: '${MYSQL_DB_PASSWORD:-password}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql:/var/lib/mysql
            - ./.docker/mysql/create-databases.sh:/docker-entrypoint-initdb.d/10-create-databases.sh
        networks:
            - database
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${MYSQL_DB_PASSWORD:-password}'
            retries: 3
            timeout: 5s
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        hostname: "rabbit"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            NAME: "rabbitmq"
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER:-guest}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD:-guest}'
        volumes:
            - ./.docker/rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
            - rabbitmq:/var/lib/rabbitmq
        networks:
            - rabbitmq
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
        container_name: elasticsearch
        ports:
            - "9200:9200"
        environment:
            discovery.type: single-node
            ELASTIC_PASSWORD: '${ELASTIC_PASSWORD:-password}'
        networks:
            - elasticsearch
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
networks:
    database:
        driver: bridge
    rabbitmq:
        driver: bridge
    elasticsearch:
        driver: bridge
volumes:
    mysql:
        driver: local
    elasticsearch:
        driver: local
    rabbitmq:
        driver: local
